# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  pull_request:
    branches: 
      - PROD-RELEASE
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Reviewer
      run: |
        PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
        REVIEWERS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/requested_reviewers" | jq --raw-output '.users')

        if [ "$REVIEWERS" != "null" ] && [ -n "$REVIEWERS" ]; then
          echo "Reviewers are added to the pull request."
        else
          echo "No reviewers are added to the pull request."
          exit 1
        fi
        
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn -B clean install
