# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  pull_request:
    branches: 
      - PROD-RELEASE
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: List reviews on the pull request
      shell: bash
      run: |
        token=${{ secrets.GITHUB_TOKEN }}
        base64AuthInfo='$token | base64 -e'
        response=$(curl --request GET \
        --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
        --header 'Authorization: $base64AuthInfo' \
        --header 'Content-Type: application/json')
        echo $response
        echo $response | jq '.[] | select(.state=="APPROVED")'
        
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn -B clean install
